name: unipose
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==1.13.1
    - torchvision>=0.14,<0.15
    - torchinfo
    - opencv-python>=4.6.0.0,<4.7.0.0
    - tqdm
    - orjson
    - numpy
    - loguru
    - pillow
    - flask
    - imageio
    - easydict
    - pycocotools
    - requests
    - pytest